--------------------------------------------------------
-- Archivo creado  - domingo-febrero-14-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONTACTO
--------------------------------------------------------

  CREATE TABLE "AGENDADB"."CONTACTO" 
   (	"IDCONTACTO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(255 BYTE), 
	"TELCASA" NUMBER(*,0), 
	"TELMOVIL" NUMBER(*,0), 
	"CORREO" VARCHAR2(255 BYTE), 
	"DIRECCION" VARCHAR2(255 BYTE), 
	"IDUSUARIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONTACTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AGENDADB"."CONTACTO_PK" ON "AGENDADB"."CONTACTO" ("IDCONTACTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CONTACTO
--------------------------------------------------------

  ALTER TABLE "AGENDADB"."CONTACTO" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "AGENDADB"."CONTACTO" ADD CONSTRAINT "CONTACTO_PK" PRIMARY KEY ("IDCONTACTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AGENDADB"."CONTACTO" MODIFY ("IDCONTACTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CONTACTO
--------------------------------------------------------

  ALTER TABLE "AGENDADB"."CONTACTO" ADD CONSTRAINT "CONTACTO_FK1" FOREIGN KEY ("IDUSUARIO")
	  REFERENCES "AGENDADB"."USUARIO" ("IDUSUARIO") ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONTACTO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AGENDADB"."CONTACTO_TRG" 
BEFORE INSERT ON CONTACTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDCONTACTO IS NULL THEN
      SELECT CONTACTO_SEQ.NEXTVAL INTO :NEW.IDCONTACTO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AGENDADB"."CONTACTO_TRG" ENABLE;
